// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package bus_test

import (
	"sync"
	"github.com/theskyinflames/cqrs-eda/pkg/bus"
)

// Ensure, that DispatchableMock does implement bus.Dispatchable.
// If this is not the case, regenerate this file with moq.
var _ bus.Dispatchable = &DispatchableMock{}

// DispatchableMock is a mock implementation of bus.Dispatchable.
//
//	func TestSomethingThatUsesDispatchable(t *testing.T) {
//
//		// make and configure a mocked bus.Dispatchable
//		mockedDispatchable := &DispatchableMock{
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedDispatchable in code that requires bus.Dispatchable
//		// and then make assertions.
//
//	}
type DispatchableMock struct {
	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockName sync.RWMutex
}

// Name calls NameFunc.
func (mock *DispatchableMock) Name() string {
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	if mock.NameFunc == nil {
		var (
			sOut string
		)
		return sOut
	}
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedDispatchable.NameCalls())
func (mock *DispatchableMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}
